
User.create!(name: 'Ife O', email: 'ifeo@poplar.com', password: '123456')
User.create!(name: 'Ant', email: 'ant@poplar.com', password: '123456')
User.create!(name: 'Abdul', email: 'abdul@poplar.com', password: '123456')
User.create!(name: 'AJM', email: 'ajm@poplar.com', password: '123456')
User.create!(name: 'Boss', email: 'boss@poplar.com', password: '123456')
User.create!(name: 'Ebe', email: 'ebe@poplar.com', password: '123456')
User.create!(name: 'Fresh', email: 'fresh@poplar.com', password: '123456')
User.create!(name: 'George', email: 'george@poplar.com', password: '123456')
User.create!(name: 'JA', email: 'ja@poplar.com', password: '123456')
User.create!(name: 'Kieran', email: 'kieran@poplar.com', password: '123456')
User.create!(name: 'Mario', email: 'mario@poplar.com', password: '123456')
User.create!(name: 'MK', email: 'mk@poplar.com', password: '123456')
User.create!(name: 'Mobs', email: 'mobs@poplar.com', password: '123456')
User.create!(name: 'Mrv', email: 'mrv@poplar.com', password: '123456')
User.create!(name: 'Nino', email: 'nino@poplar.com', password: '123456')
User.create!(name: 'Dej', email: 'dej@poplar.com', password: '123456')
User.create!(name: 'Tunji', email: 'tunji@poplar.com', password: '123456')
User.create!(name: 'Yomi', email: 'yomi@poplar.com', password: '123456')
User.create!(name: 'Ife A', email: 'ifea@poplar.com', password: '123456')
User.create!(name: 'Chicken', email: 'chicken@poplar.com', password: '123456')
User.create!(name: 'Izzy', email: 'izzy@poplar.com', password: '123456')
User.create!(name: 'Kunle', email: 'kunle@poplar.com', password: '123456')
User.create!(name: 'Adebambo', email: 'adebambo@poplar.com', password: '123456')
User.create!(name: 'Phil', email: 'phil@poplar.com', password: '123456')
User.create!(name: 'Niz', email: 'niz@poplar.com', password: '123456')
User.create!(name: 'OG', email: 'og@poplar.com', password: '123456')
User.create!(name: 'No Assist', email: 'noassist@poplar.com', password: '123456')
